In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
my_tensor = tf.random_uniform((4,4),0,1)
my_tensor

<tf.Tensor 'random_uniform/RandomUniform:0' shape=(4, 4) dtype=float32>

In [ ]:
my_var = tf.Variable(initial_value=my_tensor)
my_var

In [ ]:
with tf.Session() as sess:
    sess.run(my_var)

In [23]:
init = tf.global_variables_initializer()

In [24]:
with tf.Session() as sess:
    sess.run(init)

    res = sess.run(my_var)

In [25]:
print(res)

[[0.05939519 0.31854033 0.17173588 0.02767658]
 [0.11257327 0.23662722 0.40119803 0.30540884]
 [0.10590363 0.19298613 0.15661108 0.8351854 ]
 [0.4527433  0.9631839  0.01405144 0.38671696]]


In [27]:
#PLACEHOLDER

ph = tf.placeholder(tf.float32,shape=(None,5))